In [1]:
import pandas as pd

df = pd.read_csv("Customer_Data_Cleaned.csv")
df.head()

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Contract,Paperless_Billing,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status
0,19877-DEL,Male,35,No,Delhi,7,27,No Deal,Yes,No,...,One Year,Yes,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed
1,58353-MAH,Female,45,Yes,Maharashtra,14,13,No Deal,Yes,Yes,...,Month-to-Month,No,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed
2,25063-WES,Male,51,No,West Bengal,4,35,Deal 5,Yes,No,...,Month-to-Month,Yes,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned
3,59787-KAR,Male,79,No,Karnataka,3,21,Deal 4,Yes,No,...,Month-to-Month,Yes,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned
4,28544-TAM,Female,80,No,Tamil Nadu,3,8,No Deal,Yes,No,...,Month-to-Month,Yes,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned

In [2]:
from sklearn.preprocessing import LabelEncoder

# Create a label encoder object
le = LabelEncoder()

# Encode all categorical columns
for column in df.columns:
    if df[column].dtype == 'object':   # if column is string/categorical
        df[column] = le.fit_transform(df[column])

df.head()

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Contract,Paperless_Billing,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status
0,677,1,35,0,4,7,27,5,1,0,...,1,1,1,65.6,593.30,0.00,0,381.51,974.81,2
1,3426,0,45,1,12,14,13,5,1,1,...,0,0,1,-4.0,542.40,38.33,10,96.21,610.28,2
2,1010,1,51,0,21,4,35,4,1,0,...,0,1,0,73.9,280.85,0.00,0,134.60,415.45,0
3,3553,1,79,0,9,3,21,3,1,0,...,0,1,0,98.0,1237.85,0.00,0,361.66,1599.51,0
4,1266,0,80,0,17,3,8,5,1,0,...,0,1,1,83.9,267.40,0.00,0,22.14,289.54,0

In [3]:
from sklearn.model_selection import train_test_split

# X = all columns except Customer_Status
X = df.drop("Customer_Status", axis=1)

# y = target column
y = df["Customer_Status"]

# Split the data into train (80%) and test (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((5134, 29), (1284, 29))

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Create model
log_model = LogisticRegression(max_iter=1000)

# Train model
log_model.fit(X_train, y_train)

# Predict on test data
y_pred_log = log_model.predict(X_test)

# Accuracy
log_accuracy = accuracy_score(y_test, y_pred_log)
print("Logistic Regression Accuracy:", log_accuracy)

# Full classification report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_log))

Logistic Regression Accuracy: 0.7741433021806854

Classification Report:

              precision    recall  f1-score   support

           0       0.59      0.51      0.55       319
           1       0.56      0.51      0.53        89
           2       0.85      0.90      0.87       876

    accuracy                           0.77      1284
   macro avg       0.67      0.64      0.65      1284
weighted avg       0.76      0.77      0.77      1284

C:\Users\rajee\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Create Random Forest model
rf_model = RandomForestClassifier(n_estimators=200, random_state=42)

# Train model
rf_model.fit(X_train, y_train)

# Predict
y_pred_rf = rf_model.predict(X_test)

# Accuracy
rf_accuracy = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", rf_accuracy)

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.8333333333333334

Classification Report:

              precision    recall  f1-score   support

           0       0.71      0.58      0.64       319
           1       0.74      0.56      0.64        89
           2       0.87      0.95      0.91       876

    accuracy                           0.83      1284
   macro avg       0.77      0.70      0.73      1284
weighted avg       0.82      0.83      0.83      1284

In [25]:
# Remove any accidental column
if "Churn_Prediction" in df.columns:
    df = df.drop("Churn_Prediction", axis=1)

In [26]:
X = df.drop("Customer_Status", axis=1)
y = df["Customer_Status"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='mlogloss'
)

xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_xgb))

XGBoost Accuracy: 0.8302180685358256

Classification Report:

              precision    recall  f1-score   support

           0       0.70      0.57      0.63       319
           1       0.73      0.62      0.67        89
           2       0.87      0.95      0.91       876

    accuracy                           0.83      1284
   macro avg       0.77      0.71      0.74      1284
weighted avg       0.82      0.83      0.82      1284